# Generated by Django 4.2 on 2025-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='usage_type',
            field=models.CharField(choices=[('residential', 'سكنية'), ('commercial', 'تجارية'), ('industrial', 'صناعية'), ('agricultural', 'زراعية'), ('administrative', 'إدارية'), ('touristic', 'سياحية')], default='residential', help_text='Select the type of usage (commercial, industrial, residential)', max_length=20),
        ),
    ]
