# Generated by Django 4.2 on 2025-02-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__propert_defcdf_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'furniture_included'], name='properties__propert_04185e_idx'),
        ),
    ]
