# Generated by Django 4.2 on 2025-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_properties__propert_defcdf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='property', max_length=50),
        ),
    ]
